// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvH_IJBeCd_YWj8MToXtNW5fKQ3ptLlg',
    appId: '1:17138422201:web:339f8f3ec05d5561fb6668',
    messagingSenderId: '17138422201',
    projectId: 'news-app-v2-e2716',
    authDomain: 'news-app-v2-e2716.firebaseapp.com',
    storageBucket: 'news-app-v2-e2716.appspot.com',
    measurementId: 'G-E8VCNPHBXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYaY3TNVgbhroODrhE72u3UhQYmV-aCk',
    appId: '1:17138422201:android:4df07c5d141a44f7fb6668',
    messagingSenderId: '17138422201',
    projectId: 'news-app-v2-e2716',
    storageBucket: 'news-app-v2-e2716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfi6Z3Ixuvsdf4eBDNk09uIxZCdS4mAE',
    appId: '1:17138422201:ios:8f4e7a6069bbe40efb6668',
    messagingSenderId: '17138422201',
    projectId: 'news-app-v2-e2716',
    storageBucket: 'news-app-v2-e2716.appspot.com',
    iosClientId: '17138422201-aq0130n1jqpj2rmt02bqiu8se5cq5fcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfi6Z3Ixuvsdf4eBDNk09uIxZCdS4mAE',
    appId: '1:17138422201:ios:8f4e7a6069bbe40efb6668',
    messagingSenderId: '17138422201',
    projectId: 'news-app-v2-e2716',
    storageBucket: 'news-app-v2-e2716.appspot.com',
    iosClientId: '17138422201-aq0130n1jqpj2rmt02bqiu8se5cq5fcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );
}
