// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNQ9WX1M9VSdv8Yz5-hiio-3dCCCLWsE',
    appId: '1:883633075447:web:ee407a17526c94671d8ff2',
    messagingSenderId: '883633075447',
    projectId: 'triviazilla-97a8f',
    authDomain: 'triviazilla-97a8f.firebaseapp.com',
    storageBucket: 'triviazilla-97a8f.appspot.com',
    measurementId: 'G-25YB3Y29WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2pVN2EafIBTeI_3X3209QizCFZ4amuQY',
    appId: '1:883633075447:android:3f1009bbb6e1e5681d8ff2',
    messagingSenderId: '883633075447',
    projectId: 'triviazilla-97a8f',
    storageBucket: 'triviazilla-97a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdmU61KgdOWSvETl4bm9z-OKXWIqx2zc',
    appId: '1:883633075447:ios:89f8a4e4d042cdd51d8ff2',
    messagingSenderId: '883633075447',
    projectId: 'triviazilla-97a8f',
    storageBucket: 'triviazilla-97a8f.appspot.com',
    iosClientId: '883633075447-h376sckpphe7aofvrc37qhsqq3c1nunj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdmU61KgdOWSvETl4bm9z-OKXWIqx2zc',
    appId: '1:883633075447:ios:89f8a4e4d042cdd51d8ff2',
    messagingSenderId: '883633075447',
    projectId: 'triviazilla-97a8f',
    storageBucket: 'triviazilla-97a8f.appspot.com',
    iosClientId: '883633075447-h376sckpphe7aofvrc37qhsqq3c1nunj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBase',
  );
}
